# Generated by Django 3.0.6 on 2020-06-07 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('cms', '0022_auto_20180620_1551'),
        ('oro_plugins', '0002_galleryitem_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oro_plugins.Gallery', verbose_name='Gallery'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='youtube',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Youtube Id'),
        ),
        migrations.CreateModel(
            name='GalleryPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='oro_plugins_gallerypluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filer.Folder', verbose_name='Folder')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
